SportradarCodingExercise/Models/ErrorViewModel.cs
namespace SportradarCodingExercise.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SportradarCodingExercise/Models/Match.cs
using System.ComponentModel.DataAnnotations;

namespace Models
{
    public class Match
    {
        public Match()
        {
            // Generate a new GUID for MatchId when a Match is created
            MatchId = Guid.NewGuid();
            
            //Set startTime when a Match is created
            StartTime = DateTime.Now; 
        }
        [Required]
        public Guid MatchId { get; set; }

        [Required]
        public string HomeTeam { get; set; }

        [Required]
        public string AwayTeam { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "HomeTeamScore must be a non-negative integer.")]
        public int HomeTeamScore { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "AwayTeamScore must be a non-negative integer.")]

        public int AwayTeamScore { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime? EndTime { get; set; }
    }
}

SportradarCodingExercise/Controllers/ScoreboardController.cs
using Microsoft.AspNetCore.Mvc;
using Models;
using Services;
using SportradarCodingExercise.Models;
using System.Diagnostics;

namespace SportradarCodingExercise.Controllers
{
    public class ScoreboardController : Controller
    {
        private readonly ILogger<ScoreboardController> _logger;
        private readonly IScoreboardService _scoreboardService;  

        public ScoreboardController(ILogger<ScoreboardController> logger, IScoreboardService scoreboardService)
        {
            _logger = logger;
            _scoreboardService = scoreboardService; 
        }

        public async Task<IActionResult> Index()
        {
           return View(await _scoreboardService.GetMatchesInProgressSummary());
        }

        [HttpGet]
        public IActionResult NewMatch()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NewMatch(Match match)
        {

            if (!ModelState.IsValid)
                return View(match);

            if (match.HomeTeam.Equals(match.AwayTeam, StringComparison.CurrentCultureIgnoreCase))
            {
                // The home team and away team names are the same, handle accordingly
                ModelState.AddModelError("Same Name","Away team name must be different from the home team name.");
                return View(match);
            }

            if (await _scoreboardService.HasActiveMatch(match))
            {
                ModelState.AddModelError("ActiveMatch", "Cannot add a new match while an active match is running.");
                return View(match);
            }

            if (ModelState.IsValid)
            {
                // Continue with creating and saving the new match to the database
                await _scoreboardService.StartNewMatch(match);
                return RedirectToAction("Index");
            }
            return View(match);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateScore(Guid matchId)
        {
            var matchToUpdate = await _scoreboardService.GetMatchById(matchId);

            if (matchToUpdate == null)
            {
                return NotFound();
            }

            return View(matchToUpdate);
        }
        
        [HttpPost]
        public async Task<IActionResult> UpdateScore(Match match)
        {
            if (!ModelState.IsValid)
                return View(match);

            if (ModelState.IsValid)
            {
                await _scoreboardService.UpdateScore(match);
                return RedirectToAction("Index");
            }
            return View(match);
        }

        [HttpGet]
        public async Task<IActionResult> FinishMatch(Guid matchId)
        {
            await _scoreboardService.FinishMatch(matchId);
            return RedirectToAction("Index");
        }
    }
}

SportradarCodingExercise/Views/Scoreboard/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<Models.Match>

<div class="text-center">
    <h2 class="display-4">Football Live Matches</h2>

    <br />

    <table class="table">
    <tbody>
            @if (Model.Any())
            {
                @foreach (var match in Model)
                {
                    <tr>
                        <td>@match.HomeTeam  @match.HomeTeamScore -  @match.AwayTeam  @match.AwayTeamScore</td>
                        <td>
                            @Html.ActionLink("Update Score", "UpdateScore", new { matchId = match.MatchId }, new { @class = "btn btn-primary" })
                        </td>
                        @if (!match.EndTime.HasValue)
                        {
                            <td>
                                @Html.ActionLink("Finish Match", "FinishMatch", new { matchId = match.MatchId }, new { @class = "btn btn-warning" })
                            </td>
                        }
                    </tr>
                }
            }
            else
            {
                <p>No active matches currently.</p>
            }
        </tbody>
   </table>
    <br />
    <a class="btn btn-primary" asp-area="" asp-controller="Scoreboard" asp-action="NewMatch">Add Match</a>
</div>

SportradarCodingExercise/Views/Scoreboard/NewMatch.cshtml
@model Models.Match 

<h2>Create New Match</h2>

<form asp-action="NewMatch" method="post">
    <div class="form-group">
        <label asp-for="HomeTeam">Home Team:</label>
        <input asp-for="HomeTeam" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="AwayTeam">Away Team:</label>
        <input asp-for="AwayTeam" class="form-control" />
    </div>

    <br />

    <button type="submit" class="btn btn-primary">Create Match</button>
</form>


@if (TempData.ContainsKey("ErrorMessage"))
{
    <br />
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<br />


<div class="text-danger"> 
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
</div>

<br />

<div>
    <a asp-action="Index">Back to Matches</a>
</div>

SportradarCodingExercise/Views/Scoreboard/UpdateScore.cshtml
@model Models.Match 

<h2>Update Match Score</h2>

<form asp-action="UpdateScore" method="post">
    <div class="form-group">
        <label asp-for="HomeTeam">Home Team:</label>
        <input asp-for="HomeTeam" class="form-control" readonly />
    </div>

    <div class="form-group">
        <label asp-for="AwayTeam">Away Team:</label>
        <input asp-for="AwayTeam" class="form-control" readonly />
    </div>

    <div class="form-group">
        <label asp-for="HomeTeamScore">Home Team Score:</label>
        <input asp-for="HomeTeamScore" class="form-control" min="0"/>
    </div>

    <div class="form-group">
        <label asp-for="AwayTeamScore">Away Team Score:</label>
        <input asp-for="AwayTeamScore" class="form-control" min="0"/>
    </div>


    <input asp-for="MatchId" type="hidden" />

    <br />

    <button type="submit" class="btn btn-primary">Update Score</button>
</form>

<br />


<div class="text-danger">
    <ul>
        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <li>@error.ErrorMessage</li>
        }
    </ul>
</div>

<br />

<div>
    <a asp-action="Index">Back to Matches</a>
</div>

SportradarCodingExercise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportradarCodingExercise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportradarCodingExercise.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Scoreboard" asp-action="Index">Sportradar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scoreboard" asp-action="Index">Live Score</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scoreboard" asp-action="NewMatch">New Match</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sportradar 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>